name: setup Java test
on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'gradle'
      - run: ./gradlew build
      - run: ./gradlew ktlintCheck
      - run: ./gradlew test
